apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-cq-consumer-qa
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/llowinge/developer-charts
    targetRevision: HEAD
    path: spring-boot-application
    helm:
      values: |
        system: demo1
        component: demo1-cq-consumer
        environment: qa
        image:
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: demo1-qa
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m