apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-demo1-cq-server-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: demo1
spec:
  project: default
  source:
    repoURL: https://github.com/llowinge/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: demo1
        component: demo1-cq-server
        environment: prod
        image:
          tag: latest
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: demo1-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
