apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-demo1-openapi-api-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: demo1
spec:
  project: default
  source:
    repoURL: https://github.com/llowinge/developer-charts
    targetRevision: HEAD
    path: api-specification-pipeline
    helm:
      values: |
        domain: llowinge
        system: demo1
        component: demo1-openapi
        groupid: com.redhat.demo1
        apicurioRegistry: registry-apicurio-registry.apps.cluster-x56f8.x56f8.sandbox2954.opentlc.com
        mockRegistry: microcks-microcks.apps.cluster-x56f8.x56f8.sandbox2954.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: demo1-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
